// Copyright PolyAI Limited

package ai.poly.messaging.internal.wire

/**
 * The wire event-type vocabulary (`EVENT_TYPE_*`).
 * Decoding tolerates unknown types (returns null) rather than crashing.
 */
internal enum class WireEventType(val raw: String) {
    HEARTBEAT("EVENT_TYPE_HEARTBEAT"),
    SESSION_START("EVENT_TYPE_SESSION_START"),
    SESSION_END("EVENT_TYPE_SESSION_END"),
    SESSION_IDLE_WARNING("EVENT_TYPE_SESSION_IDLE_WARNING"),
    USER_MESSAGE("EVENT_TYPE_USER_MESSAGE"),
    USER_TYPING("EVENT_TYPE_USER_TYPING"),
    USER_END_SESSION("EVENT_TYPE_USER_END_SESSION"),
    REQUEST_POLY_AGENT_JOIN("EVENT_TYPE_REQUEST_POLY_AGENT_JOIN"),
    POLY_AGENT_JOINED("EVENT_TYPE_POLY_AGENT_JOINED"),
    POLY_AGENT_THINKING("EVENT_TYPE_POLY_AGENT_THINKING"),
    POLY_AGENT_MESSAGE("EVENT_TYPE_POLY_AGENT_MESSAGE"),
    POLY_AGENT_MESSAGE_CHUNK("EVENT_TYPE_POLY_AGENT_MESSAGE_CHUNK"),
    POLY_AGENT_LEFT("EVENT_TYPE_POLY_AGENT_LEFT"),
    POLY_AGENT_TRIGGERED_HANDOFF("EVENT_TYPE_POLY_AGENT_TRIGGERED_HANDOFF"),
    LIVE_AGENT_JOINED("EVENT_TYPE_LIVE_AGENT_JOINED"),
    LIVE_AGENT_TYPING("EVENT_TYPE_LIVE_AGENT_TYPING"),
    LIVE_AGENT_MESSAGE("EVENT_TYPE_LIVE_AGENT_MESSAGE"),
    LIVE_AGENT_LEFT("EVENT_TYPE_LIVE_AGENT_LEFT"),
    SYSTEM_MESSAGE("EVENT_TYPE_SYSTEM_MESSAGE"),
    CLIENT_HANDOFF_REQUIRED("EVENT_TYPE_CLIENT_HANDOFF_REQUIRED"),
    HANDOFF_QUEUE_STATUS("EVENT_TYPE_HANDOFF_QUEUE_STATUS"),
    HANDOFF_ACCEPTED("EVENT_TYPE_HANDOFF_ACCEPTED"),
    HANDOFF_FAILED("EVENT_TYPE_HANDOFF_FAILED"),
    HANDOFF_TIMEOUT("EVENT_TYPE_HANDOFF_TIMEOUT"),
    EVENT_BATCH("EVENT_TYPE_EVENT_BATCH"),

    // Spec-defined but not currently emitted by the server — decoded-and-dropped, never crash.
    USER_RECEIVED_MESSAGE("EVENT_TYPE_USER_RECEIVED_MESSAGE"),
    USER_READ_MESSAGE("EVENT_TYPE_USER_READ_MESSAGE"),
    POLY_AGENT_RECEIVED_MESSAGE("EVENT_TYPE_POLY_AGENT_RECEIVED_MESSAGE"),
    POLY_AGENT_READ_MESSAGE("EVENT_TYPE_POLY_AGENT_READ_MESSAGE"),
    LIVE_AGENT_RECEIVED_MESSAGE("EVENT_TYPE_LIVE_AGENT_RECEIVED_MESSAGE"),
    LIVE_AGENT_READ_MESSAGE("EVENT_TYPE_LIVE_AGENT_READ_MESSAGE"),
    SHOW_CSAT_REQUEST("EVENT_TYPE_SHOW_CSAT_REQUEST"),
    CSAT_RESPONSE("EVENT_TYPE_CSAT_RESPONSE"),
    ;

    companion object {
        private val byRaw = entries.associateBy { it.raw }
        fun fromRaw(raw: String?): WireEventType? = raw?.let { byRaw[it] }
    }
}
